config/routes.rb
Rails.application.routes.draw do
  resources :check_pages

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_page.rb
class CheckPage < ApplicationRecord
  belongs_to :site
  has_many :check_page_results

  def apply_regexp_pattern(type, body)
    site.send(type).split(/[\r\n]+/).each do |pattern|
      body = body.gsub(/#{pattern.gsub(/\//, "\\/")}/m, '')
    end
    body
  end

  def duplicate_latest_revision?(text)
    latest_revision = check_page_results.order(revision: :desc).first
    if latest_revision.present? && latest_revision.body.gsub(/\s+/, '') == text.gsub(/\s+/, '')
      true
    else
      false
    end
  end
end

app/models/check_page_result.rb
class CheckPageResult < ApplicationRecord
  belongs_to :check_page

  before_create :set_revision

  def set_revision
    revision = self.class.where(check_page_id: self.check_page_id).maximum(:revision) || 0
    self.revision = revision + 1
  end

  def clean_body
    text = body
    check_page.site.delete_patterns.strip.split(/[\r\n]+/).each do |pattern|
      text.gsub!(/#{pattern.gsub(/\//, "\\/")}/m, '')
    end
    text.gsub(/[\r\n]+/, "\n")
  end
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :check_pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_pages_controller.rb
class CheckPagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/check_pages/index.html.slim
h1 HTML diffツール
- check_time_recents = CheckPageResult.select(:checked_at).distinct.order(checked_at: :desc)
- if check_time_recents.size <= 1
  p
    | diff表示はHTML取得が2回以上必要です。(#{check_time_recents.size}回)
- else
  - latest_time = check_time_recents[0].checked_at || Time.zone.now
  - diff1_time = params[:diff1_time]&.to_datetime || check_time_recents[0].checked_at || Time.zone.now
  - diff2_time = params[:diff2_time]&.to_datetime || check_time_recents[1].checked_at || Time.zone.now

  h2 = "HTML取得履歴 revision"

  ul
  - check_time_recents.each.with_index(1) do |p, index|
    - before = index == check_time_recents.size ? nil : check_time_recents[index]
    li
      span = p.checked_at.strftime('%Y/%m/%d %H:%M:%S')
      | &nbsp;
      - if before.present?
        = link_to '[直前との比較]', check_pages_path(diff1_time: p.checked_at, diff2_time: before.checked_at)
        | &nbsp;
      - if p.checked_at != latest_time
        = link_to '[最新との比較]', check_pages_path(diff1_time: latest_time, diff2_time: p.checked_at)

  h2 = "HTML比較 diff1: #{diff1_time.strftime('%Y/%m/%d %H:%M')} <=> diff2: #{diff2_time.strftime('%Y/%m/%d %H:%M')}"

  - CheckPage.includes(:check_page_results).all.each do |page|
    - diff1 = page.check_page_results.detect{ |p| p.checked_at == diff1_time }
    - diff2 = page.check_page_results.detect{ |p| p.checked_at == diff2_time }

    h3 = page.url
    - if diff1.blank? || diff2.blank?
      p 比較対象のリビジョンがありません
    - elsif diff1.clean_body.to_s == diff2.clean_body.to_s
      p 前のリビジョンと同じです
    - else
      - diff = Diffy::SplitDiff.new(diff2.clean_body.to_s, diff1.clean_body.to_s, format: :html, allow_empty_diff: false, diff: ['--unified=3', '--ignore-all-space'])
      table.table.table-striped
        tr
          td style="width:50%" = diff2.created_at
          td style="width:50%" = diff1.created_at
        tr
          td = diff.left.html_safe
          td = diff.right.html_safe
    / - else
    /   p diffが無い
  style
    = Diffy::CSS

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UpdateCheck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body id="container">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 content-area">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>